// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: task.proto

package server_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transacao struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valor         float64                `protobuf:"fixed64,1,opt,name=valor,proto3" json:"valor,omitempty"`
	DataHora      string                 `protobuf:"bytes,2,opt,name=dataHora,proto3" json:"dataHora,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transacao) Reset() {
	*x = Transacao{}
	mi := &file_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transacao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transacao) ProtoMessage() {}

func (x *Transacao) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transacao.ProtoReflect.Descriptor instead.
func (*Transacao) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

func (x *Transacao) GetValor() float64 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Transacao) GetDataHora() string {
	if x != nil {
		return x.DataHora
	}
	return ""
}

type CriarTransacaoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transacao     *Transacao             `protobuf:"bytes,1,opt,name=transacao,proto3" json:"transacao,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CriarTransacaoRequest) Reset() {
	*x = CriarTransacaoRequest{}
	mi := &file_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriarTransacaoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriarTransacaoRequest) ProtoMessage() {}

func (x *CriarTransacaoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriarTransacaoRequest.ProtoReflect.Descriptor instead.
func (*CriarTransacaoRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

func (x *CriarTransacaoRequest) GetTransacao() *Transacao {
	if x != nil {
		return x.Transacao
	}
	return nil
}

type GetHealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthCheckResponse) Reset() {
	*x = GetHealthCheckResponse{}
	mi := &file_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthCheckResponse) ProtoMessage() {}

func (x *GetHealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthCheckResponse.ProtoReflect.Descriptor instead.
func (*GetHealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{2}
}

func (x *GetHealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetEstatisticaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeTravel    int64                  `protobuf:"varint,1,opt,name=time_travel,json=timeTravel,proto3" json:"time_travel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEstatisticaRequest) Reset() {
	*x = GetEstatisticaRequest{}
	mi := &file_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEstatisticaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEstatisticaRequest) ProtoMessage() {}

func (x *GetEstatisticaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEstatisticaRequest.ProtoReflect.Descriptor instead.
func (*GetEstatisticaRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{3}
}

func (x *GetEstatisticaRequest) GetTimeTravel() int64 {
	if x != nil {
		return x.TimeTravel
	}
	return 0
}

type GetEstatisticaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Sum           float64                `protobuf:"fixed64,2,opt,name=sum,proto3" json:"sum,omitempty"`
	Avg           float64                `protobuf:"fixed64,3,opt,name=avg,proto3" json:"avg,omitempty"`
	Min           float64                `protobuf:"fixed64,4,opt,name=min,proto3" json:"min,omitempty"`
	Max           float64                `protobuf:"fixed64,5,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEstatisticaResponse) Reset() {
	*x = GetEstatisticaResponse{}
	mi := &file_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEstatisticaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEstatisticaResponse) ProtoMessage() {}

func (x *GetEstatisticaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEstatisticaResponse.ProtoReflect.Descriptor instead.
func (*GetEstatisticaResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{4}
}

func (x *GetEstatisticaResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetEstatisticaResponse) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *GetEstatisticaResponse) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *GetEstatisticaResponse) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *GetEstatisticaResponse) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

var File_task_proto protoreflect.FileDescriptor

const file_task_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"task.proto\x12\ritauchallenge\x1a\x1bgoogle/protobuf/empty.proto\"=\n" +
	"\tTransacao\x12\x14\n" +
	"\x05valor\x18\x01 \x01(\x01R\x05valor\x12\x1a\n" +
	"\bdataHora\x18\x02 \x01(\tR\bdataHora\"O\n" +
	"\x15CriarTransacaoRequest\x126\n" +
	"\ttransacao\x18\x01 \x01(\v2\x18.itauchallenge.TransacaoR\ttransacao\"0\n" +
	"\x16GetHealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"8\n" +
	"\x15GetEstatisticaRequest\x12\x1f\n" +
	"\vtime_travel\x18\x01 \x01(\x03R\n" +
	"timeTravel\"v\n" +
	"\x16GetEstatisticaResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12\x10\n" +
	"\x03sum\x18\x02 \x01(\x01R\x03sum\x12\x10\n" +
	"\x03avg\x18\x03 \x01(\x01R\x03avg\x12\x10\n" +
	"\x03min\x18\x04 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x05 \x01(\x01R\x03max2\xd8\x02\n" +
	"\x10TransacaoService\x12N\n" +
	"\x0eCriarTransacao\x12$.itauchallenge.CriarTransacaoRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\x10LimparTransacoes\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12]\n" +
	"\x0eGetEstatistica\x12$.itauchallenge.GetEstatisticaRequest\x1a%.itauchallenge.GetEstatisticaResponse\x12Q\n" +
	"\x0eGetHealthCheck\x12\x16.google.protobuf.Empty\x1a%.itauchallenge.GetHealthCheckResponse0\x01B#Z!grpc-task-manager/proto/server_pbb\x06proto3"

var (
	file_task_proto_rawDescOnce sync.Once
	file_task_proto_rawDescData []byte
)

func file_task_proto_rawDescGZIP() []byte {
	file_task_proto_rawDescOnce.Do(func() {
		file_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)))
	})
	return file_task_proto_rawDescData
}

var file_task_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_task_proto_goTypes = []any{
	(*Transacao)(nil),              // 0: itauchallenge.Transacao
	(*CriarTransacaoRequest)(nil),  // 1: itauchallenge.CriarTransacaoRequest
	(*GetHealthCheckResponse)(nil), // 2: itauchallenge.GetHealthCheckResponse
	(*GetEstatisticaRequest)(nil),  // 3: itauchallenge.GetEstatisticaRequest
	(*GetEstatisticaResponse)(nil), // 4: itauchallenge.GetEstatisticaResponse
	(*emptypb.Empty)(nil),          // 5: google.protobuf.Empty
}
var file_task_proto_depIdxs = []int32{
	0, // 0: itauchallenge.CriarTransacaoRequest.transacao:type_name -> itauchallenge.Transacao
	1, // 1: itauchallenge.TransacaoService.CriarTransacao:input_type -> itauchallenge.CriarTransacaoRequest
	5, // 2: itauchallenge.TransacaoService.LimparTransacoes:input_type -> google.protobuf.Empty
	3, // 3: itauchallenge.TransacaoService.GetEstatistica:input_type -> itauchallenge.GetEstatisticaRequest
	5, // 4: itauchallenge.TransacaoService.GetHealthCheck:input_type -> google.protobuf.Empty
	5, // 5: itauchallenge.TransacaoService.CriarTransacao:output_type -> google.protobuf.Empty
	5, // 6: itauchallenge.TransacaoService.LimparTransacoes:output_type -> google.protobuf.Empty
	4, // 7: itauchallenge.TransacaoService.GetEstatistica:output_type -> itauchallenge.GetEstatisticaResponse
	2, // 8: itauchallenge.TransacaoService.GetHealthCheck:output_type -> itauchallenge.GetHealthCheckResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_task_proto_init() }
func file_task_proto_init() {
	if File_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_proto_goTypes,
		DependencyIndexes: file_task_proto_depIdxs,
		MessageInfos:      file_task_proto_msgTypes,
	}.Build()
	File_task_proto = out.File
	file_task_proto_goTypes = nil
	file_task_proto_depIdxs = nil
}
